import style from './Seletor.module.css';

function SelectForm({ onChange }){
    return(
        <div className={style.escolas}>
            <select name="Escolas" id="" onChange={(content) => onChange(content.target.value)}>
                    <option value="2">	YES! BARRA DA TIJUCA</option>
                    <option value="3">	YES! MANAUS-CRESPO</option>
                    <option value="4">	YES! QUEIMADOS</option>
                    <option value="5">	YES! PENHA</option>
                    <option value="6">	YES! VICENTE PIRES</option>
                    <option value="7">	YES! COPACABANA</option>
                    <option value="8">	YES! HELIÓPOLIS</option>
                    <option value="9">	YES! VILA DA PENHA</option>
                    <option value="10">	YES! CAMPO GRANDE WEST</option>
                    <option value="12">	YES! BANGU</option>
                    <option value="13">	YES! MÉIER</option>
                    <option value="15">	YES! ITAIPUAÇU</option>
                    <option value="16">	YES! LOTE XV</option>
                    <option value="17">	YES! XERÉM</option>
                    <option value="18">	YES! SEPETIBA</option>
                    <option value="19">	YES! RECREIO</option>
                    <option value="20">	YES! INDAIATUBA - JARDIM MORADA DO SOL</option>
                    <option value="24">	YES! SANTA MARIA </option>
                    <option value="29">	YES! SÃO MATEUS - JUIZ DE FORA</option>
                    <option value="30">	YES! CENTRO SBC</option>
                    <option value="31">	YES! OLINDA</option>
                    <option value="35">	YES! ALCÂNTARA</option>
                    <option value="36">	YES! ABOLIÇÃO</option>
                    <option value="37">	YES! ALDEBARAN-AL</option>
                    <option value="38">	YES! ANCHIETA</option>
                    <option value="39">	YES! ANGRA DOS REIS - CENTRO</option>
                    <option value="42">	YES! LAPA</option>
                    <option value="43">	YES! BARRA II - DOWNTOWN</option>
                    <option value="44">	YES! BARRA DE SÃO JOÃO</option>
                    <option value="45">	YES! BARRETO</option>
                    <option value="46">	YES! BELFORD ROXO</option>
                    <option value="47">	YES! BENTO RIBEIRO</option>
                    <option value="48">	YES! BOM DESPACHO</option>
                    <option value="49">	YES! BONSUCESSO</option>
                    <option value="50">	YES! BOTAFOGO</option>
                    <option value="51">	YES! CABO FRIO -  SãO CRISTóVãO</option>
                    <option value="54">	YES! CACHOEIRO DE ITAPEMIRIM</option>
                    <option value="55">	YES! CAMORIM - CRYSTAL MALL</option>
                    <option value="56">	YES! CAMPO GRANDE</option>
                    <option value="57">	YES! CASCADURA</option>
                    <option value="59">	YES! CEILÂNDIA</option>
                    <option value="62">	YES! RAMOS</option>
                    <option value="64">	YES! CURICICA</option>
                    <option value="65">	YES! DUQUE DE CAXIAS - CENTRO</option>
                    <option value="66">	YES! ENGENHEIRO PEDREIRA</option>
                    <option value="67">	YES! FONSECA</option>
                    <option value="68">	YES! FORMOSA</option>
                    <option value="70">	YES! GAMA</option>
                    <option value="71">	YES! GARDÊNIA AZUL</option>
                    <option value="72">	YES! GRAJAÚ</option>
                    <option value="73">	YES! GUADALUPE</option>
                    <option value="74">	YES! GUAPIMIRIM</option>
                    <option value="75">	YES! ICARAÍ</option>
                    <option value="76">	YES! ILHA DO GOVERNADOR</option>
                    <option value="77">	YES! IMBARIÊ</option>
                    <option value="78">	YES! IRAJÁ-RJ</option>
                    <option value="79">	YES! ITAGUAÍ</option>
                    <option value="81">	YES! JARDIM AMÉRICA</option>
                    <option value="82">	YES! JARDIM BANGU</option>
                    <option value="83">	YES! JARDIM CAMBURI</option>
                    <option value="85">	YES! JARDIM DO MAR</option>
                    <option value="86">	YES! JARDIM PRIMAVERA</option>
                    <option value="88">	YES! MACAÉ-RJ</option>
                    <option value="90">	YES! MADUREIRA-RJ</option>
                    <option value="92">	YES! MANAUS - CAMPOS ELÍSEOS</option>
                    <option value="96">	YES! MARECHAL HERMES-RJ</option>
                    <option value="97">	YES! MÉIER II-RJ</option>
                    <option value="99">	YES! MIGUEL COUTO</option>
                    <option value="100">YES! NILÓPOLIS - RJ</option>
                    <option value="102">YES! NOVA IGUAÇU-RJ</option>
                    <option value="103">YES! OLARIA – RJ</option>
                    <option value="104">YES! PACIÊNCIA-RJ</option>
                    <option value="105">YES! PALMAS - TO</option>
                    <option value="106">YES! PARANOÁ – DF</option>
                    <option value="108">YES! PAVUNA-RJ</option>
                    <option value="110">YES! PEDRA DE GUARATIBA-RJ</option>
                    <option value="112">YES! PETRÓPOLIS-RJ</option>
                    <option value="114">YES! ITAIPU</option>
                    <option value="115">YES! PRAIA DE MAUÁ</option>
                    <option value="116">YES! REALENGO-RJ</option>
                    <option value="117">YES! RIO COMPRIDO-RJ</option>
                    <option value="118">YES! RIO DAS OSTRAS</option>
                    <option value="119">YES! RIO DAS PEDRAS - RJ</option>
                    <option value="120">YES! ROCHA MIRANDA-RJ</option>
                    <option value="121">YES! ROCINHA-RJ</option>
                    <option value="123">YES! SANTA CRUZ DA SERRA-RJ</option>
                    <option value="125">YES! SÃO CRISTOVÃO-RJ</option>
                    <option value="126">YES! SÃO GONÇALO-RJ</option>
                    <option value="128">YES! SÃO PEDRO DA ALDEIA -RJ</option>
                    <option value="129">YES! SARACURUNA-RJ</option>
                    <option value="131">YES! TAQUARA-RJ</option>
                    <option value="132">YES! TERESÓPOLIS - R</option>J
                    <option value="133">YES! TIJUCA - RJ</option>
                    <option value="134">YES! TRÊS RIOS - RJ</option>
                    <option value="137">YES! VILAR DOS TELES-RJ</option>
                    <option value="138">YES! VILA SÃO LUIS</option>
                    <option value="141">YES! VISTA ALEGRE-RJ</option>
                    <option value="142">YES! VOLTA REDONDA- RJ</option>
                    <option value="143">YES! PATIO - AL</option>
                    <option value="144">YES! ITABORAÍ</option>
                    <option value="148">YES! SANTA CECÍLIA</option>
                    <option value="151">YES! INHAPI</option>
                    <option value="152">YES! UNAMAR</option>
                    <option value="153">YES! ASSUNÇÃO</option>
                    <option value="154">YES! SANTA CRUZ</option>
                    <option value="155">YES! VILA SANTA CECILIA - VOLTA REDONDA</option>
                    <option value="156">YES! VILA ISABEL - RJ</option>
                    <option value="157">YES! PINHEIRAL - RJ</option>
                    <option value="158">YES! ITATIAIA - RJ</option>
                    <option value="159">YES! MESQUITA - RJ</option>
                    <option value="160">YES! PAULISTA - JANGA - PE</option>
                    <option value="161">YES! PIABETÁ - RJ</option>
                    <option value="162">YES! MACHADO - MG</option>
                    <option value="163">YES! OSÓRIO - RS</option>
                    <option value="164">YES! BRAÇO DO NORTE - SC</option>
                    <option value="165">YES! FAZENDA RIO GRANDE - PR</option>
                    <option value="167">YES! TUBARAO - SC</option>
                    <option value="168">YES! CASCATINHA</option>
                    <option value="170">YES! ARARUAM</option>A
                    <option value="171">YES! SILVA JARDIM</option>
                    <option value="172">YES! MARICÁ</option>
            </select>
        </div>
    );
}

export default SelectForm;